config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
 
  
  root 'simple_pages#landing_page'
  get 'products/index'
  get 'simple_pages/index'
  get 'simple_pages/about'
  get 'simple_pages/faq'
  get 'simple_pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product

  
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def index
    @orders = Order.includes(:product).all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
  end

  def create
  end

  def destroy
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
    @products = Product.limit(3)
  end

  def about
  end

  def faq
  end

  def contact
  end

  def landing_page
   @products = Product.limit(3)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drive</title>
    <!-- Bootstrap v5.0.1 cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", simple_pages_about_path %></li>
        <li><%= link_to "Contact", simple_pages_contact_path %></li>
      </ul>
    </nav>

  <%= yield %>

  <footer>
    &copy; 2018 Bike Berlin
  </footer>
  
   <!-- Bootstrap Bundle with Popper -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/index.html.erb
<h1>Orders</h1>

<div class="container-fluid">
  <div class="row">
    <% @orders.each do |order| %>
    <div class="col-sm">
      <h1>Order # <%= order.id %>:
      <%= link_to order.product.name, order %>
      </h1>

      <p><%= order.product.description %></p>

      <strong>$ <%= order.product.price %></strong>

    </div><!-- /col -->
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <h2>Order Information</h2>
    <strong>Order ID: </strong>
    <%= @order.id %>
    <strong>Product Name: </strong>
    <%= @order.product.name %>
    <strong>Product Price: </strong>
    <strong>Total Price: </strong>
    <%=number_to_currency(@order.total/100.to_f) %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>
  
  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>
  
  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
 
    <div class="row">
      <% @products.each do |products| %>
        <div class="col-sm something1"><a href="#">
          <h1><%= products.name%></h1></a>
           <%= image_tag("red.jpg", class: "img-fluid") %>
            <p class="para-size"><%= products.description%></p>
            <p><%= products.price%></p>
            <strong>42</strong>
        </div><!-- /col -->
      <% end %>
    </div>
    

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="container-fluid">
  <div class="something">
   
      <%= render @products %>
   
  </div> 
</div>


<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/about.html.erb
<h1>SimplePages#about</h1>
<p>Find me in app/views/simple_pages/about.html.erb</p>

app/views/simple_pages/contact.html.erb
<h1>SimplePages#contact</h1>
<p>Find me in app/views/simple_pages/contact.html.erb</p>

app/views/simple_pages/faq.html.erb
<h1>SimplePages#faq</h1>
<p>Find me in app/views/simple_pages/faq.html.erb</p>

app/views/simple_pages/index.html.erb
<h1>SimplePages#index</h1>
<p>Find me in app/views/simple_pages/index.html.erb</p>

app/views/simple_pages/landing_page.html.erb
<h2>Featured Product:</h2>


<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <% @products.each do |product| %>
    <div class="carousel-item <%= "active" if product == @products.first %>">
      <%= image_tag("hd.jpg") %>
      <div class="carousel-caption d-none d-md-block">
        <%= product.name %>
      </div>
    </div>
  <% end %>
  </div>

<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>